### PR TITLE
Add TypeScript typings

### LINKED ISSUE #51: Consider releasing TypeScript typings
I would love to use this library in TypeScript code.

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

### PR DESCRIPTION
**Pull request by aluanhaddad**
Resolves #51

### CODE REVIEW

**Comment by Igmat** [comment]
Will this PR resolved in nearest future, or it makes sense to add this typings to `DefinitelyTyped`?

**Comment by aluanhaddad** [comment]
@ahmadnassri is there anything more I can do here? Should I add tests?

**Comment by ahmadnassri** [comment]
@aluanhaddad sorry for the delay, it's now been merged

**Comment by aluanhaddad** [comment]
Not a problem. Thank you much.

**Comment by ahmadnassri** [comment]
released in [`v3.4.0`](https://github.com/ahmadnassri/glob-promise/releases/tag/v3.4.0)

**Comment by Izhaki** [comment]
Hmmm.... this works:

    import * as glob from 'glob-promise';
    glob('../../api/**/*.ts');

**Pull request merged**
